version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data